sonar.projectKey=PROJECT-API
sonar.projectName=PROJECT-API
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=squ_dae4d8868a509b39a9d79828a7a34726c3bcaf9f