# Generated by Django 4.2 on 2025-10-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacorasORM',
            fields=[
                ('bita_id', models.AutoField(primary_key=True, serialize=False)),
                ('bita_inversion', models.TextField(blank=True, null=True)),
                ('bita_cronograma', models.TextField(blank=True, null=True)),
                ('bita_estado_sea', models.TextField(blank=True, null=True)),
                ('bita_otros', models.TextField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
                ('user_created_at', models.CharField(blank=True, max_length=150, null=True)),
                ('user_edited_at', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tbl_bitacoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComunasORM',
            fields=[
                ('comu_id', models.AutoField(primary_key=True, serialize=False)),
                ('comu_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('comu_codigo', models.CharField(blank=True, max_length=150, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_comunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactoProyectoORM',
            fields=[
                ('copr_id', models.AutoField(primary_key=True, serialize=False)),
                ('copr_tipo', models.IntegerField(blank=True, null=True)),
                ('copr_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('edited_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_contacto_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactosORM',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('cont_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('cont_telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('cont_correo', models.CharField(blank=True, max_length=150, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('carc_id', models.IntegerField(blank=True, null=True)),
                ('cont_es_interno', models.BooleanField(blank=True, null=True)),
                ('carc_descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('cont_observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_contactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CronogramaORM',
            fields=[
                ('cron_id', models.AutoField(primary_key=True, serialize=False)),
                ('cron_obs', models.CharField(blank=True, max_length=255, null=True)),
                ('cron_etapa', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_cronograma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescripcionORM',
            fields=[
                ('desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('desc_objetivo', models.TextField(blank=True, null=True)),
                ('desc_resumen', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
                ('desc_ubicacion', models.TextField(blank=True, null=True)),
                ('desc_vidautil', models.TextField(blank=True, null=True)),
                ('desc_obras', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_descripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpresaORM',
            fields=[
                ('empr_id', models.AutoField(primary_key=True, serialize=False)),
                ('empr_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('empr_rut', models.CharField(max_length=30)),
                ('empr_razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('empr_ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('empr_direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('empr_telefono', models.CharField(blank=True, max_length=60, null=True)),
                ('empr_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('empr_correo_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('empr_observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('empr_no_inscrita', models.IntegerField(default=0)),
                ('pais_id', models.IntegerField(blank=True, null=True)),
                ('comu_id', models.CharField(blank=True, max_length=40, null=True)),
                ('aeco_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.PositiveIntegerField(default=0)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProyectoORM',
            fields=[
                ('pro_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_estado_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSeaORM',
            fields=[
                ('esea_id', models.AutoField(primary_key=True, serialize=False)),
                ('esea_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('pais_id', models.IntegerField(blank=True, null=True)),
                ('esea_is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_estado_sea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstatusContingenciaORM',
            fields=[
                ('estatus_cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_cont_nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_estatus_contingencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneracionDistribuidaORM',
            fields=[
                ('dist_id', models.AutoField(primary_key=True, serialize=False)),
                ('dist_nombre', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tbl_generacion_distribuida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedioAmbienteORM',
            fields=[
                ('mamb_id', models.AutoField(primary_key=True, serialize=False)),
                ('mamb_emp_pres_proyecto', models.CharField(blank=True, max_length=250, null=True)),
                ('mamb_tipo_proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('mamb_fecha_presentacion', models.IntegerField(blank=True, null=True)),
                ('mamb_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('mamb_plazo_evaluacion', models.IntegerField(blank=True, null=True)),
                ('mamb_dias_legales', models.CharField(blank=True, max_length=255, null=True)),
                ('mamb_dias_totales', models.CharField(blank=True, max_length=255, null=True)),
                ('ppro_id', models.IntegerField(blank=True, null=True)),
                ('mamb_enlace_sea', models.CharField(blank=True, max_length=255, null=True)),
                ('is_history', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('mamb_fecha_calificacion', models.IntegerField(blank=True, null=True)),
                ('mamb_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_last_medio_ambiente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaisORM',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('pais_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('pais_codigo', models.CharField(blank=True, max_length=6, null=True)),
                ('pais_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosORM',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('prod_unidad_medida', models.CharField(blank=True, max_length=150, null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinciasORM',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('prov_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectoORM',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.TextField(blank=True, null=True)),
                ('pro_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_capacidad_produccion', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_ubicacion', models.TextField(blank=True, null=True)),
                ('region_incidencia_proyecto', models.TextField(blank=True, null=True)),
                ('pro_monto_inversion', models.FloatField(blank=True, null=True)),
                ('pro_descripcion', models.TextField(blank=True, null=True)),
                ('is_covid_affected', models.IntegerField(default=0)),
                ('is_green_hydrogen', models.IntegerField(default=0)),
                ('is_deleted', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
                ('user_created_at', models.IntegerField(blank=True, null=True)),
                ('user_edited_at', models.IntegerField(blank=True, null=True)),
                ('pro_cron_fecha', models.IntegerField(blank=True, null=True)),
                ('pro_diferido', models.IntegerField(default=0)),
                ('confidencial', models.IntegerField(default=0)),
                ('mindha', models.IntegerField(blank=True, null=True)),
                ('sea_afectado', models.IntegerField(blank=True, null=True)),
                ('desaladora', models.IntegerField(default=0)),
                ('codigo_bip', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sea', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionORM',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('reg_codigo', models.CharField(blank=True, max_length=150, null=True)),
                ('reg_representacion', models.CharField(blank=True, max_length=20, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionHidrogenoORM',
            fields=[
                ('relacion_hidrogeno_id', models.AutoField(primary_key=True, serialize=False)),
                ('relacion_hidrogeno_nombre', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'tbl_relacion_hidrogeno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelListadoEquiposDescripcionORM',
            fields=[
                ('lieq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rel_listado_equipos_descripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelListadoObrasDescripcionORM',
            fields=[
                ('liob_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rel_listado_obras_descripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelProductoProyectoORM',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop_descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('prop_cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'rel_producto_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectorEconomicoORM',
            fields=[
                ('seco_id', models.AutoField(primary_key=True, serialize=False)),
                ('seco_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_sector_economico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInversionORM',
            fields=[
                ('tinv_id', models.AutoField(primary_key=True, serialize=False)),
                ('tinv_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('oinv_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_tipo_inversion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipologiasORM',
            fields=[
                ('tplo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tplo_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tplo_codigo', models.CharField(blank=True, max_length=150, null=True)),
                ('subeco_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.PositiveIntegerField(blank=True, null=True)),
                ('edited_at', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_tipologias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoObraORM',
            fields=[
                ('tiob_id', models.AutoField(primary_key=True, serialize=False)),
                ('tiob_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('edited_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_tipo_obras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProyectoORM',
            fields=[
                ('tpro_id', models.AutoField(primary_key=True, serialize=False)),
                ('tpro_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('is_deleted', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_tipo_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleoORM',
            fields=[
                ('pro', models.OneToOneField(db_column='pro_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='empleo', serialize=False, to='project.proyectoorm')),
                ('emp_con_nocal', models.IntegerField(blank=True, null=True)),
                ('emp_con_profe', models.IntegerField(blank=True, null=True)),
                ('emp_con_tec', models.IntegerField(blank=True, null=True)),
                ('emp_con_total', models.IntegerField(blank=True, null=True)),
                ('emp_con_nocal_peak', models.IntegerField(blank=True, null=True)),
                ('emp_con_profe_peak', models.IntegerField(blank=True, null=True)),
                ('emp_con_tec_peak', models.IntegerField(blank=True, null=True)),
                ('emp_con_total_peak', models.IntegerField(blank=True, null=True)),
                ('emp_ope_nocal', models.IntegerField(blank=True, null=True)),
                ('emp_ope_profe', models.IntegerField(blank=True, null=True)),
                ('emp_ope_tec', models.IntegerField(blank=True, null=True)),
                ('emp_ope_total', models.IntegerField(blank=True, null=True)),
                ('emp_ope_nocal_peak', models.IntegerField(blank=True, null=True)),
                ('emp_ope_profe_peak', models.IntegerField(blank=True, null=True)),
                ('emp_ope_tec_peak', models.IntegerField(blank=True, null=True)),
                ('emp_ope_total_peak', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_empleo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtapasProyectoORM',
            fields=[
                ('pro', models.OneToOneField(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.proyectoorm')),
                ('ing_conc_inicio', models.DateField(blank=True, null=True)),
                ('ing_conc_fin', models.DateField(blank=True, null=True)),
                ('ing_basica_inicio', models.DateField(blank=True, null=True)),
                ('ing_basica_fin', models.DateField(blank=True, null=True)),
                ('ing_detalle_inicio', models.DateField(blank=True, null=True)),
                ('ing_detalle_fin', models.DateField(blank=True, null=True)),
                ('cons_inicio', models.DateField(blank=True, null=True)),
                ('cons_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_etapas_proyecto',
            },
        ),
        migrations.CreateModel(
            name='GeoORM',
            fields=[
                ('pro', models.OneToOneField(db_column='pro_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.proyectoorm')),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('created_at', models.BigIntegerField(blank=True, null=True)),
                ('edited_at', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_geo',
            },
        ),
    ]
